freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-4-release-amd64
  install_script:
    pkg install -y gmake py39-pexpect
  build_script:
    gmake
  test_script:
    - gmake test PYTHON_CMD=python3.9
